
@api = http://localhost:3000/products



GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "name": "cpu",
    "description": "hp",
    "quantity": "200"
}

### Getting a product
GET {{api}}/11

### Deleting a product
DELETE {{api}}/9

### get total products
GET {{api}}/count 

### update a product
PUT {{api}}/11
Content-Type: application/json

{
    "name": "Asus",
    "description": "cpu",
    "quantity": "50"
}
